### ISSUE TITLE
Recommends deprecated function persistFile

### ISSUE THREAD

**Issue by erikd** [snoyberg/yesodbook#5]
In the Persistent chapter of the book, just after the code in the "Code Generation" section suggests the use of `persistFile` which seems deprecated in favour of `persistWithFile`.

**Comment by snoyberg** [comment]
Good catch, fixed in: https://github.com/yesodweb/yesodweb.com-content/commit/16d135f485a3ec6ea2c933d16443ee7dc5c8f06c
